// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuyiF2dHAA-kgiL1HmBIizYlKgRJrwCo',
    appId: '1:876831130489:web:6493cb3920c55b24c165a8',
    messagingSenderId: '876831130489',
    projectId: 'quiz-app-new-34eaf',
    authDomain: 'quiz-app-new-34eaf.firebaseapp.com',
    storageBucket: 'quiz-app-new-34eaf.appspot.com',
    measurementId: 'G-LY6G9BNW4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5Teufq-oIaJFjTGrZlItcEJEoSzxnKE',
    appId: '1:876831130489:android:2bdae5da86985352c165a8',
    messagingSenderId: '876831130489',
    projectId: 'quiz-app-new-34eaf',
    storageBucket: 'quiz-app-new-34eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2nUZd0p7wOFsAfwAPS83-4h-e0ppEzgw',
    appId: '1:876831130489:ios:9b2f436bc21839c8c165a8',
    messagingSenderId: '876831130489',
    projectId: 'quiz-app-new-34eaf',
    storageBucket: 'quiz-app-new-34eaf.appspot.com',
    androidClientId: '876831130489-kivuhdd8fhmn06arfl39mcivq58n3teg.apps.googleusercontent.com',
    iosClientId: '876831130489-llsk5b190l4jfvoov6tjjr63jtlnmmd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2nUZd0p7wOFsAfwAPS83-4h-e0ppEzgw',
    appId: '1:876831130489:ios:9b2f436bc21839c8c165a8',
    messagingSenderId: '876831130489',
    projectId: 'quiz-app-new-34eaf',
    storageBucket: 'quiz-app-new-34eaf.appspot.com',
    androidClientId: '876831130489-kivuhdd8fhmn06arfl39mcivq58n3teg.apps.googleusercontent.com',
    iosClientId: '876831130489-llsk5b190l4jfvoov6tjjr63jtlnmmd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
